import type { Participant, TransportLog, SyncQueueItem } from "./data-store";

export const SAMPLE_PARTICIPANTS: Participant[] = [
  {
    id: "p-001",
    fullName: "Aaliyah Brennan",
    ndisId: "430 118 244",
    dob: "1992-03-14",
    iddsi: { liquids: 2, foods: 5 },
    mobility: "Wheelchair",
    allergies: ["Peanuts"],
    flags: ["Choking risk"],
    primaryContact: { name: "Marcus Brennan", relation: "Brother", phone: "0412 334 901" },
    notes: "Requires thickened fluids and supervised meals at all times.",
  },
  {
    id: "p-002",
    fullName: "Benjamin Olajide",
    ndisId: "430 220 117",
    dob: "1987-11-02",
    iddsi: { liquids: 0, foods: 7 },
    mobility: "Independent",
    allergies: [],
    flags: [],
    primaryContact: { name: "Folake Olajide", relation: "Mother", phone: "0433 102 887" },
    notes: "Prefers morning transport runs.",
  },
  {
    id: "p-003",
    fullName: "Chen Wei Lin",
    ndisId: "430 555 028",
    dob: "1975-06-21",
    iddsi: { liquids: 3, foods: 4 },
    mobility: "Walking frame",
    allergies: ["Shellfish", "Dairy"],
    flags: ["Diabetic"],
    primaryContact: { name: "Mei Lin", relation: "Daughter", phone: "0498 220 114" },
    notes: "Insulin schedule documented in care plan.",
  },
  {
    id: "p-004",
    fullName: "Daniela Petrov",
    ndisId: "430 990 412",
    dob: "2001-01-30",
    iddsi: { liquids: 0, foods: 7 },
    mobility: "Independent",
    allergies: [],
    flags: ["Behaviour support"],
    primaryContact: { name: "Anna Petrov", relation: "Mother", phone: "0421 887 330" },
    notes: "",
  },
  {
    id: "p-005",
    fullName: "Eli Whitford",
    ndisId: "430 401 779",
    dob: "1968-09-09",
    iddsi: { liquids: 4, foods: 3 },
    mobility: "Wheelchair",
    allergies: ["Latex"],
    flags: ["Choking risk", "PEG feed"],
    primaryContact: { name: "Susan Whitford", relation: "Spouse", phone: "0418 220 555" },
    notes: "Strict NBM after 7pm.",
  },
  {
    id: "p-006",
    fullName: "Farida Hassan",
    ndisId: "430 612 003",
    dob: "1994-04-18",
    iddsi: { liquids: 1, foods: 6 },
    mobility: "Walking stick",
    allergies: [],
    flags: [],
    primaryContact: { name: "Omar Hassan", relation: "Father", phone: "0455 720 118" },
    notes: "",
  },
  {
    id: "p-007",
    fullName: "Gregory Okafor",
    ndisId: "430 778 540",
    dob: "1982-12-05",
    iddsi: { liquids: 0, foods: 7 },
    mobility: "Independent",
    allergies: ["Sesame"],
    flags: [],
    primaryContact: { name: "Linda Okafor", relation: "Sister", phone: "0412 990 224" },
    notes: "",
  },
  {
    id: "p-008",
    fullName: "Hannah Whitlock",
    ndisId: "430 119 887",
    dob: "1955-07-22",
    iddsi: { liquids: 2, foods: 5 },
    mobility: "Wheelchair",
    allergies: ["Penicillin"],
    flags: ["Diabetic"],
    primaryContact: { name: "Tom Whitlock", relation: "Son", phone: "0408 113 552" },
    notes: "Family request: call before pickup.",
  },
];

const today = new Date();
const isoToday = today.toISOString();
const isoYesterday = new Date(today.getTime() - 24 * 3600 * 1000).toISOString();

export const SAMPLE_TRANSPORT_LOGS: TransportLog[] = [
  {
    id: "t-001",
    participantId: "p-002",
    pickupOdometer: 48210,
    dropoffOdometer: 48227,
    passengerPresent: true,
    status: "Arrived",
    timestamp: isoToday,
    notes: "On time.",
  },
  {
    id: "t-002",
    participantId: "p-006",
    pickupOdometer: 48227,
    dropoffOdometer: 48241,
    passengerPresent: true,
    status: "Arrived",
    timestamp: isoToday,
    notes: "",
  },
  {
    id: "t-003",
    participantId: "p-004",
    pickupOdometer: 48241,
    dropoffOdometer: 48241,
    passengerPresent: false,
    status: "No-show",
    timestamp: isoToday,
    notes: "Knocked twice, no answer. Phoned guardian.",
  },
  {
    id: "t-004",
    participantId: "p-001",
    pickupOdometer: 47980,
    dropoffOdometer: 48004,
    passengerPresent: true,
    status: "Arrived",
    timestamp: isoYesterday,
    notes: "",
  },
  {
    id: "t-005",
    participantId: "p-008",
    pickupOdometer: 48004,
    dropoffOdometer: 48022,
    passengerPresent: true,
    status: "Arrived",
    timestamp: isoYesterday,
    notes: "Family contacted before pickup.",
  },
];

export const SAMPLE_SYNC_ITEMS: SyncQueueItem[] = [
  {
    id: "s-001",
    type: "transport_log",
    createdAt: new Date(today.getTime() - 12 * 60 * 1000).toISOString(),
    status: "pending",
    attempts: 0,
    payload: { participantId: "p-002", status: "Arrived", km: 17 },
  },
  {
    id: "s-002",
    type: "iddsi_change",
    createdAt: new Date(today.getTime() - 45 * 60 * 1000).toISOString(),
    status: "retrying",
    attempts: 2,
    payload: { participantId: "p-005", liquids: 4, foods: 3 },
  },
  {
    id: "s-003",
    type: "participant_update",
    createdAt: new Date(today.getTime() - 3 * 3600 * 1000).toISOString(),
    status: "failed",
    attempts: 5,
    payload: { participantId: "p-003", field: "allergies", value: ["Shellfish", "Dairy"] },
    error: "Network timeout after 30s",
  },
];
