import { writeToLedger } from "@/lib/api/ledger";
import { resolveStaffIdWithFallback } from "@/lib/data-store";
import { assembleComplianceSection } from "./compliance";
import { assembleDayCentreSection } from "./day-centre";
import { assembleDocumentStubs } from "./documents";
import { assembleIncidentsSection } from "./incidents";
import { auditDate, auditDateTime } from "./format";
import {
  type AuditIdentityMode,
  auditIdentity,
  withAuditIdentity,
} from "./identity";
import {
  createAuditPdf,
  pdfAddHeading,
  pdfAddKeyValues,
  pdfAddLines,
  pdfToBytes,
} from "./pdf";
import { assembleTripEvidence, assembleTripsSection } from "./trips";
import type {
  AuditDateRange,
  AuditPackBuildResult,
  AuditPackFile,
  AuditPackProgressFn,
  AuditPackSections,
} from "./types";
import { DEFAULT_AUDIT_SECTIONS } from "./types";
import { buildZipBlob, downloadBlob } from "./zip";

function rootReadme(
  range: AuditDateRange,
  generatedBy: string,
  mode: AuditIdentityMode,
): string {
  const identityBlock =
    mode === "deid"
      ? `IDENTITY MODE — DE-IDENTIFIED AUDITOR COPY
Participant and staff names/IDs are replaced with stable pack-local codes
(P-001, S-001, …) so CSVs still join. Venue names, dates, process evidence,
and operational statuses are unchanged.

WARNING: Free-text fields (issue descriptions, Hub notes, ledger metadata JSON)
are NOT scrubbed and may still contain real names. Treat as confidential.
This copy is for desktop review / external USB preview — not a substitute for
named sample evidence on site.

Generated-by staff code: ${generatedBy}
`
      : `IDENTITY MODE — NAMED (authoritative)
This pack contains named participant and staff records for quality audit use
under your organisation's custody. Do not email unencrypted. Prefer USB /
secure portal transfer.

Generated by staff id: ${generatedBy}
`;

  return `Yada Connect — NDIS Audit Pack
================================

Generated: ${auditDateTime(new Date())}
Date range: ${auditDate(range.from)} → ${auditDate(range.to)}

${identityBlock}
Folder map
----------
00_INDEX.pdf                 Table of contents + completeness flags
01_Incidents_Complaints/     Issues + Hub notes timeline + resolution ledger
02_Day_Centre/               Sessions, issues+notes, §11 manifest trips/legs, ledger
03_Trips/                    Per-trip evidence (rolls, boarding, issues+notes, manifest)
04_Compliance/               Compliance assets + resolution ledger
05_Policies_Procedures/      Reserved — BL-092 (stub until library approved)
06_Onboarding_Training/      Reserved — BL-065 + BL-051 (stub until onboarded)

This pack supports NDIS quality / Practice Standards evidence — not MYOB claim
generation. Outing trips are non-NDIS for claiming but remain duty-of-care
evidence.
`;
}

function buildIndexPdf(
  range: AuditDateRange,
  summary: AuditPackBuildResult["summary"],
  mode: AuditIdentityMode,
): Uint8Array {
  const doc = createAuditPdf("00 — NDIS Audit Pack Index");
  let y = 32;
  y = pdfAddKeyValues(
    doc,
    [
      ["Date range", `${auditDate(range.from)} → ${auditDate(range.to)}`],
      [
        "Identity mode",
        mode === "deid" ? "De-identified (P-/S- codes)" : "Named (real)",
      ],
      ["Incidents / issues", String(summary.incidentCount)],
      ["Day Centre sessions", String(summary.daySessionCount)],
      ["Trips", String(summary.tripCount)],
      ["Compliance assets", String(summary.complianceAssetCount)],
      [
        "Policies & Onboarding libraries",
        summary.documentsComplete
          ? "Loaded"
          : "INCOMPLETE — stub folders only (BL-092 / BL-065)",
      ],
    ],
    y,
  );
  y = pdfAddHeading(doc, "How to use", y + 2);
  pdfAddLines(
    doc,
    [
      "1. Copy this ZIP to a USB stick or secure share for the Approved Quality Auditor.",
      "2. Start with 00_INDEX and 01_Incidents_Complaints for complaints/incidents outcomes.",
      "3. Open 03_Trips/<date>_<slug>/trip_evidence.pdf when asked about a specific outing.",
      "4. 05_ and 06_ stay stubs until policy and onboarding document libraries ship.",
      mode === "deid"
        ? "5. De-id copy: free-text may still identify people — archive the named pack as authoritative."
        : "5. Named pack is the authoritative evidence archive for this export.",
    ],
    y,
  );
  return pdfToBytes(doc);
}

export async function buildNdisAuditPack(opts: {
  range: AuditDateRange;
  sections?: Partial<AuditPackSections>;
  onProgress?: AuditPackProgressFn;
  /** When set, only emit that trip's folder (plus root readme/index). */
  singleEventId?: string;
  /** BL-093 — default named; deid = auditor desktop / external USB preview. */
  identityMode?: AuditIdentityMode;
}): Promise<AuditPackBuildResult> {
  const mode: AuditIdentityMode = opts.identityMode ?? "named";

  return withAuditIdentity(mode, async () => {
    const sections: AuditPackSections = {
      ...DEFAULT_AUDIT_SECTIONS,
      ...opts.sections,
    };
    const files: AuditPackFile[] = [];
    const summary: AuditPackBuildResult["summary"] = {
      incidentCount: 0,
      daySessionCount: 0,
      tripCount: 0,
      complianceAssetCount: 0,
      documentsComplete: false,
    };

    const staffId = await resolveStaffIdWithFallback();
    const generatedByLabel = auditIdentity().staffKey(staffId) || staffId;
    opts.onProgress?.("Preparing pack…");

    if (opts.singleEventId) {
      opts.onProgress?.("Building trip evidence…");
      const trip = await assembleTripEvidence(opts.singleEventId);
      files.push(...trip.files);
      summary.tripCount = 1;
    } else {
      if (sections.incidents) {
        opts.onProgress?.("Incidents & complaints…");
        const inc = await assembleIncidentsSection(opts.range);
        files.push(...inc.files);
        summary.incidentCount = inc.count;
      }
      if (sections.dayCentre) {
        opts.onProgress?.("Day Centre…");
        const day = await assembleDayCentreSection(opts.range);
        files.push(...day.files);
        summary.daySessionCount = day.sessionCount;
      }
      if (sections.trips) {
        opts.onProgress?.("Trips…");
        const trips = await assembleTripsSection(opts.range, opts.onProgress);
        files.push(...trips.files);
        summary.tripCount = trips.tripCount;
      }
      if (sections.compliance) {
        opts.onProgress?.("Compliance…");
        const comp = await assembleComplianceSection(opts.range);
        files.push(...comp.files);
        summary.complianceAssetCount = comp.assetCount;
      }
      if (sections.documentStubs) {
        opts.onProgress?.("Document library stubs…");
        files.push(...assembleDocumentStubs());
      }
    }

    files.unshift({
      path: "00_README.txt",
      content: rootReadme(opts.range, generatedByLabel, mode),
    });
    files.unshift({
      path: "00_INDEX.pdf",
      content: buildIndexPdf(opts.range, summary, mode),
    });

    const stamp = opts.range.to.replace(/-/g, "");
    const suffix = mode === "deid" ? "_deid" : "";
    const filename = opts.singleEventId
      ? `Yada_TripEvidence_${stamp}${suffix}.zip`
      : `Yada_AuditPack_${stamp}${suffix}.zip`;

    void writeToLedger({
      actionType: "AUDIT_PACK_EXPORTED",
      category: "CENTRE",
      severity: "INFO",
      staff_id: staffId,
      metadata: {
        range_from: opts.range.from,
        range_to: opts.range.to,
        single_event_id: opts.singleEventId ?? null,
        identity_mode: mode,
        summary,
        filename,
      },
    });

    return { files, filename, summary };
  });
}

export async function downloadNdisAuditPack(opts: {
  range: AuditDateRange;
  sections?: Partial<AuditPackSections>;
  onProgress?: AuditPackProgressFn;
  singleEventId?: string;
  identityMode?: AuditIdentityMode;
}): Promise<AuditPackBuildResult> {
  const result = await buildNdisAuditPack(opts);
  opts.onProgress?.("Zipping…");
  const blob = await buildZipBlob(result.files);
  downloadBlob(blob, result.filename);
  return result;
}
