/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ParticipantsRouteImport } from './routes/participants'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DayRouteImport } from './routes/day'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DayRoute = DayRouteImport.update({
  id: '/day',
  path: '/day',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/day': typeof DayRoute
  '/events': typeof EventsRoute
  '/governance': typeof GovernanceRoute
  '/manifest': typeof ManifestRoute
  '/participants': typeof ParticipantsRoute
  '/staff': typeof StaffRoute
  '/sync': typeof SyncRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/day': typeof DayRoute
  '/events': typeof EventsRoute
  '/governance': typeof GovernanceRoute
  '/manifest': typeof ManifestRoute
  '/participants': typeof ParticipantsRoute
  '/staff': typeof StaffRoute
  '/sync': typeof SyncRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/day': typeof DayRoute
  '/events': typeof EventsRoute
  '/governance': typeof GovernanceRoute
  '/manifest': typeof ManifestRoute
  '/participants': typeof ParticipantsRoute
  '/staff': typeof StaffRoute
  '/sync': typeof SyncRoute
  '/transport': typeof TransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/day'
    | '/events'
    | '/governance'
    | '/manifest'
    | '/participants'
    | '/staff'
    | '/sync'
    | '/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/day'
    | '/events'
    | '/governance'
    | '/manifest'
    | '/participants'
    | '/staff'
    | '/sync'
    | '/transport'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/day'
    | '/events'
    | '/governance'
    | '/manifest'
    | '/participants'
    | '/staff'
    | '/sync'
    | '/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DayRoute: typeof DayRoute
  EventsRoute: typeof EventsRoute
  GovernanceRoute: typeof GovernanceRoute
  ManifestRoute: typeof ManifestRoute
  ParticipantsRoute: typeof ParticipantsRoute
  StaffRoute: typeof StaffRoute
  SyncRoute: typeof SyncRoute
  TransportRoute: typeof TransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day': {
      id: '/day'
      path: '/day'
      fullPath: '/day'
      preLoaderRoute: typeof DayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DayRoute: DayRoute,
  EventsRoute: EventsRoute,
  GovernanceRoute: GovernanceRoute,
  ManifestRoute: ManifestRoute,
  ParticipantsRoute: ParticipantsRoute,
  StaffRoute: StaffRoute,
  SyncRoute: SyncRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
